firstPullRequest
BestStartapers2018/game1 pull request #1
Opened 2018-03-29 23:28 UTC by DenisAltruist

Lol

2018-03-29 23:32 UTC, petuhovskiy commented
Оно работает, уже хорошо

2018-03-29 23:46 UTC, petuhovskiy requested changes
Пока что нужно исправить сборку

2018-03-29 23:46 UTC, petuhovskiy commented on index.html
> +</html>
Сейчас html статичен, ссылается на внешние зависимости и `script3.js` который не прописан в сборщике и как следствие сборка не работает.
Решение: исправить html и починить сборку
```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>gameTmp</title>

  <!-- build:css main.min.css -->
  <link rel="stylesheet" href="css/main.css">
  <!-- /build -->
</head>

<body>

  <div id="gameTmp-game" class="game"></div>

  <!-- build:js phaser.min.js -->
  <script src="node_modules/phaser-ce/build/phaser.min.js"></script>
  <!-- /build -->

  <!-- build:js bundle.min.js -->
  <script src="bundle.js"></script>
  <!-- /build -->

</body>
</html>
```

2018-03-29 23:46 UTC, petuhovskiy commented on package.json
> +    "build:js": "browserify -d -e src/main.js -t [babelify --comments false --presets env] | uglifyjs -cm > build/bundle.min.js",
Сейчас код располагается в `script3.js`, поэтому нужно просто заменить все `src/main.js` на `script3.js`

2018-03-29 23:46 UTC, petuhovskiy commented on package.json
> +    "phaser": "^3.2.1",
Лишняя зависимость, нужно удалить

2018-03-30 16:33 UTC, petuhovskiy requested changes
Можно немного отформатировать код, а остальное пускай пока что так остается.

2018-03-30 16:33 UTC, petuhovskiy commented on src/main.js
> +var FRICTION = 10000000;
В ES6 почти во всех случаях можно обойтись без `var`.
Поменять `var` на `let` или `const`.

2018-03-30 16:33 UTC, petuhovskiy commented on src/main.js
> +var cntOfExtraBoxes = 0;
Аналогично с `var`

2018-03-30 16:33 UTC, petuhovskiy commented on src/main.js
> +	game.load.image('coalBox', 'assets/coalBox.png');
Выравнивание прыгает, неплохо бы выровнять.

2018-03-30 16:50 UTC, petuhovskiy approved these changes

2018-03-30 16:55 UTC, petuhovskiy commented
Fixes #3

2018-03-30 16:57 UTC, DenisAltruist commented
Fixes #3

2018-03-30 17:09 UTC, merged